name: finanzeapp-frontend
services:
  react:
    build:
      dockerfile: ./Dockerfile
      labels:
        - "app.finanze.build=${GIT_HASH}"
    ports:
      - 127.0.0.1:3300:3000
    env_file:
      - path: ./.env
        required: true
